name: testci

on: 
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo ${{ secrets.TEST_SECRET }} > out.txt
      - name: Upload artifact
        id: upload_helm_chart
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: out.txt